/*Instrucitons for the If ELSE practice in Coddy: 
Your task is to initialize variable windStatus based on the conditions:

"Calm" if wind is smaller than 8,
"Breeze" if wind is between 8 and 31 (including 8 and 31).
"Gale" if wind is between 32 and 63 (including 32 and 63)
"Storm" otherwise

*/

//This part below generated by the course
const wind = parseInt(inp)
let windStatus = "unset"

// Write your code below


// my code below......I DID IT after DAYSSSSSSS of trying to figure this out yayayayaayay😝
if (wind < 8) { 
    windStatus = "Calm";
    } else if (wind >= 8 && wind <=31) { 
        windStatus = "Breeze"; 
    } else if (wind >= 32 && wind <= 63) { 
        windStatus = "Gale"; 
    } else { 
        windStatus = "Storm"; 
    }
